version: '3.8'
services:
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
          - ./grafana_data:/data/grafana
        environment:
          GF_SECURITY_ADMIN_PASSWORD: pass
          GF_RENDERING_SERVER_URL: http://renderer:8081/render
          GF_RENDERING_CALLBACK_URL: http://grafana:3000/
          GF_LOG_FILTERS: rendering:debug
        ports:
          - 3000:3000

    loki:
      image: grafana/loki:2.8.4
      container_name: loki
      volumes:
        - ./loki/loki.yml:/tmp/loki.yml
      command: -config.file=/tmp/loki.yml
      ports:
        - 3100:3100

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        command: --config.file=/tmp/prometheus.yml
        volumes:
         -  ./prometheus/prometheus.yml:/tmp/prometheus.yml
        ports:
         - 9090:9090

    alert_manager:
       image: quay.io/prometheus/alertmanager:latest
       container_name: alert_manager
       ports:
        - 9093:9093

    blackbox_exporter:
        image: quay.io/prometheus/blackbox-exporter:latest
        container_name: blackbox_exporter
        restart: always
        command: --config.file=/etc/blackbox_exporter/config.yml
        volumes:
          - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml
        ports:
          - 9115:9115
    
    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        ports:
          - 9100:9100

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        ports:
        - 8080:8080
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
        - redis
        
    redis:
        image: redis:latest
        container_name: redis
        ports:
        - 6379:6379